# Generated by Django 5.1.4 on 2026-05-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='absences',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='failures',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='study_time',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='weak_topic',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
