# Generated by Django 5.1.4 on 2026-05-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(choices=[('Algebra', 'Algebra'), ('Calculus', 'Calculus'), ('Programming', 'Programming'), ('Statistics', 'Statistics')], max_length=100)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=100)),
                ('resource_type', models.CharField(choices=[('Video', 'Video'), ('PDF', 'PDF'), ('Practice', 'Practice')], max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
